function [bestSeam,bestScore] = getBestSeam( G, seams )
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%getBestSeam function: return the best seam based on the score of the
%gradient
%Usage:
%    bestSeam = getBestSeam( G, seams );
%Input:
%   -G: gradient of the image generated by getGradient function
%   -seams: the seams that are extracted using getSeams function
%Output:
%   -bestSeam: the interesting seam (best score).
%   -bestScore: cost of the best seam
%Citation: Avidan, Shai, and Ariel Shamir. "Seam carving for content-aware
%image resizing. ACM Transactions on graphics (TOG). Vol. 26. No. 3.
%ACM, 2007"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Author: Mahmoud Afifi, York University.

scores=sum(seams(:,:,3),2);
bestScore=min(scores);
bestSeam=seams(find(scores==bestScore),:,:);
if size(bestSeam,1)>1
    ind=randi(size(bestSeam,1));
    bestSeam=bestSeam(ind,:,:);
end
end

